<a href="https://colab.research.google.com/github/OlandezVoador/SI_atividades/blob/gold/Lab%201%20-%20Introdu%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sistemas Inteligentes

## Lab 1 - Introdução

* Metodologia de trabalho
* Apresentação das ferramentas
* Comandos usuais da linguagem Python

### Identificação do Aluno

#### Nome Completo

Felipe Banes Lopes Ferreira

#### RA

21076215

## 1. Importando bibliotecas, pacotes e funções

In [1]:
# Biblioteca de álgebra linear
import numpy as np

# Pacote de funções para plot
import matplotlib.pyplot as plt

# Função de Mínimos Quadrados ('Least Squares')
from scipy.linalg import lstsq

<font color='red'>**Exercício:**</font>  importe a função **hamming** do pacote **signal** pertencente à biblioteca **scipy** já apelidando-a como "ham".

In [2]:
from scipy.signal import hamming as ham

## 2. Tipos de dados

### 2.1. Inteiro

In [4]:
type(3)

int

### 2.2. Float

In [5]:
type(3.23213)

float

### 2.3. String

In [3]:
type('Testing')

str

### 2.4. List

In [4]:
type([1,2,3])

list

### 2.5. Array

In [5]:
type(np.array([1,2,3]))

numpy.ndarray

<font color='red'>**Exercício:**</font>  Crie uma variável ou estrutura de qualquer tipo, então verifique se ela está, de fato, com o tipo almejado por você no ato da criação.

In [6]:
a = 10
type(a)

int

## 3. Operações básicas

### 3.1. Soma

In [7]:
5 + 9

14

### 3.2. Subtração

In [8]:
3 - 7

-4

### 3.3. Multiplicação

In [9]:
2 * 4

8

### 3.4. Divisão

In [10]:
15 / 3

5.0

<font color='red'>**Exercício:**</font>  efetue algum cálculo envolvendo todas as operações básicas; tudo em uma mesma linha de código.

In [12]:
### INSIRA AQUI O CÓDIGO ###
3-4+2*8/2

7.0

## 4. Manipulações com Listas

### 4.1. Criando uma lista

Estes são alguns exemplos típicos de listas em Python. L1 é uma lista simples; L2 é uma lista de listas de mesmo tamanho; L3 é uma lista de listas de diferentes tamanhos; e L4 é uma lista vazia.

In [16]:
L1 = [1, 3, 7, 29]

L2 = [[1,2,3], [4,5,6], [7,8,9]]

L3 = [[1], [2,3], [4,5,6]]

L4 = []


### 4.2. Adicionando itens ao fim de uma lista

In [ ]:
L_teste = []

L_teste.append(5)
L_teste.append([1,3])
L_teste.append([[7,2], [9, 0]])


print(L_teste)

### 4.3. Adicionando o conteúdo de uma lista ao fim de outra

In [22]:
L_teste_1 = []

L_teste_2 = [3,4,5]
L_teste_3 = [9,1,2,3,4,1]

L_teste_1.extend(L_teste_2)

print("L_teste_1 = " + str(L_teste_1))

L_teste_1.extend(L_teste_3)

print("L_teste_1 final = " + str(L_teste_1))

L_teste_1 = [3, 4, 5]
L_teste_1 final = [3, 4, 5, 9, 1, 2, 3, 4, 1]


### 4.4. Encontrando a posição do primeiro item com determinado valor na lista

In [23]:
L_teste = [7, 1, 2, 5, 2, 8, 9, 0, 3]

L_teste.index(5)

3

### 4.5. Ordenando os itens da lista

In [24]:
L_teste = [3, 1, 4, 6, 7, 9]

L_teste.sort()

print(L_teste)

L_teste.sort(reverse=True)

print(L_teste)

[1, 3, 4, 6, 7, 9]
[9, 7, 6, 4, 3, 1]


<font color='red'>**Exercício:**</font> crie duas novas listas de diferentes tamanhos, então adicione os elementos da segunda lista ao final da primeira lista e imprima a lista resultante e a posição de um dos números dessa lista. Por fim, ordene a lista resultante e imprima a lista e a posição do mesmo valor.

In [32]:
### INSIRA AQUI O CÓDIGO ###
a = [4,99]
b = [59,5]

print("1° versão "+str(a))

a.extend(b)

print("2° versão - uniao "+str(a))

a.sort()
print("3° versão - ordenada "+str(a))


1° versão [4, 99]
2° versão - uniao [4, 99, 59, 5]
3° versão - ordenada [4, 5, 59, 99]


## 5. Manipulações com Arrays (vetores ou matrizes)

### 5.1. Criando duas matrizes de dimensões 3x3

In [34]:
A = np.array([ 
    [3, 4, 5], 
    [6, 7, 8], 
    [9, 0, 1] 
])
B = np.array([ [0, 1, 2], [3, 4, 5], [6, 7, 8] ])

### 5.2. Exibindo as matrizes

#### 5.2.1. Por completo

In [42]:
A

array([[3, 4, 5],
       [6, 7, 8],
       [9, 0, 1]])

In [36]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 5.2.2. Parcialmente

In [37]:
A[:, :2]

array([[3, 4],
       [6, 7],
       [9, 0]])

In [ ]:
B[1:, 1]

### 5.3. Soma de matrizes

In [46]:
A + B

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15,  7,  9]])

### 5.4. Subtração de matrizes

In [47]:
A - B

array([[ 3,  3,  3],
       [ 3,  3,  3],
       [ 3, -7, -7]])

### 5.5. Multiplicação de matriz por escalar

In [ ]:
2 * A

### 5.6. Produto escalar

In [43]:
(A, B)

(array([[3, 4, 5],
        [6, 7, 8],
        [9, 0, 1]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

### 5.7. Produto vetorial

In [44]:
np.cross(A, B)

array([[  3,  -6,   3],
       [  3,  -6,   3],
       [ -7, -66,  63]])

### 5.8. Transposição

#### 5.8.1. Utilizando a biblioteca Numpy

In [45]:
np.transpose(A)

array([[3, 6, 9],
       [4, 7, 0],
       [5, 8, 1]])

#### 5.8.2. Utilizando a transposição do próprio Python

In [50]:
A
A.T

array([[3, 6, 9],
       [4, 7, 0],
       [5, 8, 1]])

### 5.9. Inversão

In [49]:
np.invert(A)

array([[ -4,  -5,  -6],
       [ -7,  -8,  -9],
       [-10,  -1,  -2]])

### 5.10. Verificando as dimensões ('shape') da matriz

In [ ]:
A.shape

### 5.11. Adicionando novas linhas ao fim de uma matriz já existente

In [ ]:
np.row_stack((A, np.array([1, 3, 7])))

### 5.12. Adicionando novas colunas ao fim de uma matriz já existente

In [ ]:
np.column_stack((A, np.array([1, 3, 7])))

<font color='red'>**Exercício:**</font> crie dois arrays 3x2, então calcule o produto escalar de um deles pela transposta do outro e imprima a primeira linha do array resultante.

In [ ]:
### INSIRA AQUI O CÓDIGO ###

## 6. Gerando um sinal e plotando gráficos

### 6.1. Gerando um vetor de 50 posições, igualmente "espaçadas", com valores de 0 a 6$\pi$

In [ ]:
x = np.linspace(0, 6 * np.pi, 50)

### 6.2. Gerando um sinal senoidal a partir das posições do vetor anteriormente criado

In [ ]:
y = np.sin(x)

### 6.3. Plotando o sinal

In [ ]:
plt.plot(x, y, label='cos(t)')
plt.legend()
plt.title('Sinal Senoidal')
plt.xlabel('Tempo')
plt.ylabel('Valor')

### 6.4 Plotando o gráfico de dispersão ('Scatter')

In [ ]:
plt.scatter(x, y, label='cos(t)')
plt.legend()
plt.title('Sinal Senoidal')
plt.xlabel('Tempo')
plt.ylabel('Valor')

### 6.5. Plotando gráficos de hastes ou ramos ('Stem')

In [ ]:
markerline, stemlines, baseline = plt.stem(x, y, label='cos(t)')
plt.setp(markerline, color='r')
plt.setp(stemlines, color='g', linewidth=3)
plt.setp(baseline, color='b', linewidth=2)
plt.legend()
plt.title('Sinal Senoidal')
plt.xlabel('Tempo')
plt.ylabel('Valor')

### 6.6. Plotando múltiplos gráficos em uma única figura

In [ ]:
plt.plot(x, y, label='cos(t)')
plt.plot(x, 2 * y, label='2 * cos(t)')
plt.legend()
plt.title('Sinais Senoidais')
plt.xlabel('Tempo')
plt.ylabel('Valor')

<font color='red'>**Exercício:**</font> gere três sinais diferentes, então faça o plot, o gráfico de dispersão e o diagrama de hastes; apenas um tipo para cada sinal.

In [ ]:
### INSIRA AQUI O CÓDIGO ###

## 7. Condicionais (if, elif e else)

In [ ]:
n = 5

if n < 4:
    print('Low')
elif n == 4:
    print('Mid')
else:
    print('High')

## 8. Laços de repetição

### 8.1. For

In [ ]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
K = [1, 3, 7, 11, 19]

for x in K:
    print(x)

In [ ]:
KK = [[1,3,2,5], [4,8,7,12]]

for x in KK:
    print(x)

### 8.2. While

In [ ]:
i = 0

while i < 5:
    print(i)
    i += 1

## 9. Definindo funções

### 9.1. Simples

Esta é a definição de um exemplo bastante simples, que apenas retorna o resultado da soma dos dois números de entrada.

In [ ]:
def soma(a, b):
    return a + b

Agora, que a função já está definida, ela está pronta para ser usada neste Notebook, independentemente da célula em que seja invocada.

In [ ]:
soma(7, 8)

### 9.2. Com valores padrão

Funções em Python podem ter variáveis de entrada com valores padrão, o que faz com que o usuário não precise entrar com o valor correspondente à variável de entrada em questão, desde que se deseje utilizar o valor padrão.

In [ ]:
def soma_padrao(a, b=3):
    return a + b

Pela função soma_padrao(), se forem utilizados os dois argumentos de entrada, o seu funcionamento é o mesmo da função soma(), porém, ao se utilizar um único argumento de entrada, a função passa a considerar o valor padrão para a segunda entrada (não fornecida pelo usuário).

In [ ]:
soma_padrao(7, 8)

In [ ]:
soma_padrao(7)

<font color='red'>**Exercício:**</font> crie uma função que utilize ao menos um condicional e ao menos um laço de repetição, além de ter pelo menos uma variável de entrada com valor padrão. Então, em outra célula, utilize a função criada para mostrar que funciona adequadamente.

In [ ]:
### INSIRA AQUI O CÓDIGO DA FUNÇÃO ###

In [ ]:
### INSIRA AQUI O CÓDIGO DE TESTE ###

## 10. Ajuda

#### Procurem consultar as documentações correspondentes para entender como funcionam as funções.

* [Python](https://docs.python.org/3.6/)
* [Numpy](https://docs.scipy.org/doc/numpy/reference/)
* [Scipy](https://docs.scipy.org/doc/scipy/reference/)
* [Scikit-Learn](http://scikit-learn.org/stable/documentation.html)

Utilizando a própria linguagem Python também é possível obter ajuda quando se quer saber como funciona uma dada função. Para isso, basta utilizar a função $help()$ com o nome da função que deseja pesquisar. Por exemplo, caso se deseje saber mais sobre a função $linspace()$ da biblioteca Numpy, pode-se pesquisar assim:

In [ ]:
help(np.linspace)

#### Outras fontes também podem ser consultadas.

* [StackOverflow](https://stackoverflow.com/)
* [Quora](https://www.quora.com/)